function fitMLEtoExperiment(directory,thresh)
% fitMLEtoExperiment(directory)
%
% Go through a directory containing .mat files that were exported with
% aggregateReversals. There should be one .mat file for each "run" 
% (which itself may have once been composed of multiple recordings)
% 
% All of these runs should have been of the same experiment. 
%
% This script combines them all, graphs them and fits an exponential.
%
% 
disp('Welcome. Hit enter to close all windows and continue..');
pause;
close all;
files=ls([directory '\*.mat']);

h = waitbar(0,'Aggregating runs...');
steps = size(files,1);

if ~exist('thresh')
    thresh=-1;
end

figure(1);
title('Reversal Magnitude');

figure(2);
title('Binary Response');
for k=1:steps
    
    waitbar(k/ steps)

    
    disp(['Loading ' files(k,:) ' ...' ]);

    
    %Load the file
    load( [directory '\'  files(k,:)],'-mat')
    disp('loaded!');
    %Check to make sure we are dealing with a mat file that was generated
    %from the mindcontrol preview program
    if ( ~exist('t') || ~exist('short'))
        disp([directory '\'  files(k,:) '  does not seem to be a file generated by aggregateReversals.m as expected']  )
        continue
    end
   
    
    %plot the reversal magnitude
    figure(1);
    hold on;
    plot(t,short,'*','MarkerEdgeColor',[rand, rand, rand]);
    
    
    %calculate binary response
    r=zeros(size(short));
    r(find(short<thresh))=1;
    
    %plot binary response
    figure(2)
    hold on;
    plot(t,r,'*','MarkerEdgeColor',[rand, rand, rand]);
    
    clear('t','short');
end

close(h)
    disp('Goodbye.');
